### ISSUE TITLE
Great results but too computational heavy.

### ISSUE THREAD

**Issue by Sweetapocalyps3** [Camb-ai/MARS5-TTS#14]
Results seem excellent, but it definitely requires too much VRAM to be run. It would be great if you could make a lighter version keeping as much quality as you can.

Thanks.

**Comment by akshhack** [comment]
Hey @Sweetapocalyps3 thanks for the feedback! Can you share any samples you created in #Discussions.
:re efficiency, this is just the very first release and we intend for the community to roll out a lighter version asap.

**Comment by johnwick123f** [comment]
Yep, quality is amazing but it is pretty slow and takes more vram then most other tts libraries. That's probably expected as this is a newly released codebase! 

Great work btw!

**Comment by akshhack** [comment]
Hey @johnwick123f thanks for the validation and feedback. Yes, we're an extremely new repo and the optimizations, benchmarks and more are on their way. I'd love for you to suggest / participate in areas where said optimizations can be made. Thank you!
