### ISSUE TITLE
Provide a docker image for the code

### ISSUE THREAD

**Issue by vitonsky** [Camb-ai/MARS5-TTS#15]
Hi, i found this project on HN, it looks interesting, but i don't want to manually setup all the things to just check the quality of your solution.

The modern delivery standard is a docker image, because it allow to any people run your code with a single command.
Check another projects from HN like https://github.com/gabotechs/MusicGPT

So please, create docker file that will encapsulate whole configuration and let users to try your solution simple and fast

**Comment by akshhack** [comment]
Hey @vitonsky thanks for the suggestion!

Until someone in the community puts up a docker setup (which we're considering just to do pypi), you can check the quality of the TTS through our samples demo:
https://179c54d254f7.ngrok.app/

We try to explain what current "SOTA" is and what's available as both closed source and open-source, versus what the intention and ability of MARS is. Additionally, here's a loom about the same -- https://www.loom.com/share/a6e7c6658f9f4b09a696926a98dd6fcc
