### ISSUE TITLE
Support for other languages

### ISSUE THREAD

**Issue by Ch3my** [Camb-ai/MARS5-TTS#20]
Thanks for the great project! Looks like only English voice generation works well, generating audio in spanish results in a native english speaking voice talking spanish.

Also, I did testing with a spanish reference voice with similar results.

Are there plans to support other languages?

**Comment by akshhack** [comment]
Hey @Ch3my, as we mentioned, we've open-sourced the English language. We're going to be open sourcing the rest incrementally but you can find them on studio.camb.ai today already

**Comment by Ch3my** [comment]
I'm looking forward to it! Thanks
