### ISSUE TITLE
Where is the output saved?

### ISSUE THREAD

**Issue by 4DeepThought2** [Camb-ai/MARS5-TTS#23]
I feel like an idiot here.  Running this on Windows (WSL with conda).  Where in the heck does the audio file output get saved?

**Comment by nolanblew** [comment]
The output doesn't seem to be saved anywhere - just in memory.

You can save the output by first importing soundfile:
```python
import soundfile as sf
```

Then at the end of the script, put:
```python
sf.write('./output.wav', output_audio, sr) # replace output.wav with your output path if you want to change it
```

If you had a lot of trouble like I did getting very small or empty audio, make sure that you have your transcript filled out correctly, or set `deep_clone` to False (though in my experiments, the results were not anywhere close to the reference audio)
