### ISSUE TITLE
Deep Clone and generation longer than 12s

### ISSUE THREAD

**Issue by skirdey** [Camb-ai/MARS5-TTS#24]
Currently, when using deep cloning, and maybe when not - the model starts producing artifacts after 12 seconds of total new audio generation. Was wondering if it is expected for current model checkpoint, or needs further troubleshooting?

**Comment by akshhack** [comment]
@skirdey adding a few updates in 2 days that should help with stability. Thanks

**Comment by RF5** [comment]
Hi @skirdey , please  check the latest checkpoint release, it should be quite a bit more stable for pronunciation when using deep clone. Hope that helps!

**Comment by skirdey** [comment]
@RF5 sadly the quality got q
[output_mandatory_9_20240624_232539_0312d69b5cd84cb1877ddc100046cd83.zip](https://github.com/user-attachments/files/15962274/output_mandatory_9_20240624_232539_0312d69b5cd84cb1877ddc100046cd83.zip)
uite worse, now the audio comes with artifacts just after 5-6 seconds

**Comment by skirdey** [comment]
Here is the code I use for generation
```
# Load the MARS5 model
def load_mars5_model():
    mars5, config_class = torch.hub.load('Camb-ai/mars5-tts', 'mars5_english', trust_repo=True, force_reload=True)
    return mars5, config_class

# Generate new audio using MARS5
def generate_audio(mars5, config_class, text, reference_audio, ref_transcript=None, deep_clone=True):
    cfg = config_class(deep_clone=deep_clone, rep_penalty_window=100,
                      top_k=100, temperature=0.7, freq_penalty=3)
    ar_codes, output_audio = mars5.tts(text, reference_audio, ref_transcript, cfg=cfg)
    return output_audio
    ```
    
    The quality degradation is consistent after 3-4 seconds with the latest checkpoint across all attempts. Previous checkpoint I had the quality degradation at around 12 seconds threshold.

**Comment by RF5** [comment]
Hmm, a bit hard to debug this as from our evaluations we haven't seen such degradataion. Could you send us the audio reference and text that is giving you trouble and we can look into it?

**Comment by skirdey** [comment]
Sure, attached a reference archive, it has a shorter clip for cloning, result of the cloning (degradation at 12s) and the text that the original speaker says. 
[test.zip](https://github.com/user-attachments/files/15967774/test.zip)

**Comment by thhung** [comment]
Yes, I can confirm. The quality is varied a lot. When the audio is good, it does not follow the voice reference. When it follows the voice reference, the audio has many artifacts, not even pronounce properly. For the the code, I simply used your colab notebook.

**Comment by RF5** [comment]
Ahh thanks @skirdey for the files, I think I see the problem here. This is an issue with the public demo. Long story short, the way the public demo is setup, if you input long texts, it naively splits it up if the sentence gets too long (around the 12s mark), and then performs inference on each sentence in turn, concatenating the result. The problem is, when doing inference on the 2nd chunk (12s onwards in your clip), it naively uses the first chunk output as reference, which isn't pure human speech, but rather generated outputs. This causes quality degradations.

Can you try your sample example again in the colab demo, or locally, and see if the same problem occcurs? One of the tasks we're looking for contributions on is better way to handle long-form generation while not eating up tons of GPU memory.

**Comment by skirdey** [comment]
I believe I've been using local inference so far, and degradation happens as well.

If I give 10 seconds of reference audio, then degradation starts at around 3-4 seconds.

If I gave 5-6 seconds reference audio, degradation starts at around 12 second. 

I haven't tried long form text, the text Ive provided is just entire reference speaker transcript. For generation only short parts of it are used that match length of reference speech.

**Comment by skirdey** [comment]
> @skirdey Would you mind sharing the specific examples that did not work out well for you? The reference samples, input text and output samples, if you can. Also, some details on the set up you're using.

sure, will share

**Comment by skirdey** [comment]
[artifact_gens.zip](https://github.com/user-attachments/files/16077934/artifact_gens.zip)

Archive with source audio, its transcript, and 7 out of 7 generations with noise and artifacts. 

The generation itself is done via:
```
# Pick whether you want a deep or shallow clone. Set to False if you don't know prompt transcript or want fast inference. Set to True if you know transcript and want highest quality.
deep_clone = True
# Below you can tune other inference settings, like top_k, temperature, top_p, etc...
cfg = config_class(deep_clone=deep_clone, rep_penalty_window=100,
                      top_k=100, temperature=0.7, freq_penalty=3)

ar_codes, output_audio = mars5.tts(new_text, wav,
          ref_transcript,
          cfg=cfg)
```
