### ISSUE TITLE
mars5_demo in Collab issue

### ISSUE THREAD

**Issue by PS-AI** [Camb-ai/MARS5-TTS#27]
The output audio is not synthesized.

**Comment by akshhack** [comment]
Hey @PS-AI it has been working well for quite a few people -- can you please help me understand your problem a bit better.

**Comment by EasyAimLock** [comment]
RuntimeError: scatter(): Expected self.dtype to be equal to src.dtype

**Comment by Adibian** [comment]
Hi @akshhack 
I have the same problem. I just ran your Collb code but 9 seconds of silence is synthesized! Also, it lasted a long time to synthesize it (I don't know if it is normal or not for MARS5)
![test](https://github.com/Camb-ai/MARS5-TTS/assets/42696179/f01c59a9-2c22-4de9-b3b0-1193bf811fd4)

**Comment by pieterscholtz** [comment]
@PS-AI @Adibian 
We've merged a fix for this. For it to take effect, you may need to delete your torch hub cache before trying it again, e.g.:
`rm -rf ~/.cache/torch/hub/Camb-ai_mars5-tts_master`
Please note that this is a CPU only bug and that inference on CPU will be quite slow.
