### ISSUE TITLE
Any way to manually force phonemes? Issue with incorrect utterances of common words

### ISSUE THREAD

**Issue by platform-kit** [Camb-ai/MARS5-TTS#29]
Tried to generate some outputs using this sentence from the demo's instructions:

`We provide several generation candidates when you synthesize text, and attempt to pick the best one on the right.`

The word "several" simply WILL NOT come out correctly. It comes out as "seeval," "seeral," "seel," etc.

I am sure this is a byproduct of being an early release, but I want to flag it now as I think that in addition to training there ought to be a way to manually pass in pronunciation data using [ssml](https://cloud.google.com/text-to-speech/docs/ssml)

Example:

``` 
 <phoneme alphabet="ipa" ph="ˌmænɪˈtoʊbə">manitoba</phoneme>
 <phoneme alphabet="x-sampa" ph='m@"hA:g@%ni:'>mahogany</phoneme>
``` 

This way, if the autoregressive model repeatedly guesses incorrectly (i.e. on an unusual name), there is a way to force the right result.

**Comment by platform-kit** [comment]
@akshhack I'm not sure. I used the demo linked on the readme, yesterday. So if you updated the demo with the new checkpoints, then, yes.

**Comment by NourAlMerey** [comment]
@akshhack good idea. Will do that.

**Comment by platform-kit** [comment]
@akshhack Here's a sample from the replicate demo


Input:
`We provide several generation candidates when you synthesize text, and attempt to pick the best one on the right.`

Ref Audio:
https://files.catbox.moe/be6df3.wav

Transcript:
`We actually haven't managed to meet demand.`

Output:
https://files.catbox.moe/07ru0x.mp3

API version:
https://replicate.com/camb-ai/mars5-tts/versions/097744a80bc07de9293fd35f9997bb86dbbf68a11a1d98c3e1c2295ee5bb89ab

**Comment by platform-kit** [comment]
Hi guys, just bumping this as I was able to ship a demo on Replicate that uses the new weights and returns audio in the browser based UI

Here's the sample - as you can see it is still not producing correct prosody:
https://replicate.com/platform-kit/mars5-tts?prediction=e0469h915nrgg0cg9fkra5pc60

[predict.py](https://github.com/Camb-ai/MARS5-TTS/blob/ea914a9951e8437a045e0ab0ec626c4d7d3d6796/cog/predict.py)

[hubconf.py with latest weights](https://github.com/Camb-ai/MARS5-TTS/blob/ea914a9951e8437a045e0ab0ec626c4d7d3d6796/hubconf.py)

**Comment by arnavmehta7** [comment]
Hey @platform-kit , would you like to make the PR to this file: https://github.com/Camb-ai/MARS5-TTS/blob/master/cog/predict.py
Otherwise I will take it up :)
