### ISSUE TITLE
20GB VRAM requirement

### ISSUE THREAD

**Issue by petergerten** [Camb-ai/MARS5-TTS#31]
Hi,

can somebody explain how this requires ~20GB VRAM?
For 750M+450M params that seems very strange. The readme indicates that there is room for optimization but I would like to understand what the main problem is.

**Comment by RF5** [comment]
Hi @petergerten , the main issue is we don't have a card limit in the code on the amount of characters you can generate, so the 20GB VRAM is a rather crude, rough, upper bound. For short pieces of text and references, you can probably get away with much less. We'll get to proper VRAM testing with different inference lengths and update the readme shortly. Hope that helps!

**Comment by drzraf** [comment]
I wished these overall 1.2G parameters could load on a low-end GPU. Sadly, they didn't hold within 1.8GB VRAM, but **why so**?
(btw the README file wasn't actually updated to reflect this current limitation)
