### ISSUE TITLE
Give exact versions of dependencies

### ISSUE THREAD

**Issue by nikitashekhov** [Camb-ai/MARS5-TTS#33]
Hi

Could you give the exact versions of dependencies in `requirements.txt`?

While installing on Mac, I am always getting errors because of the versions and need to google it every time to fix. 
For example, numpy 2.0 was just released, but your lib does not work with it, so everyone need to use numpy==1.26, and so on.

**Comment by akshhack** [comment]
@nikitashekhov if you have a `requirements.txt` that worked, I'd recommend pasting it here for the community to take help from. Thanks!

**Comment by nikitashekhov** [comment]
@akshhack no, I don't have, I was not able to build.

**Comment by nikitashekhov** [comment]
@akshhack I was not able to start. Sorry

**Comment by akshhack** [comment]
no worries, @nikitashekhov take your time.
