### ISSUE TITLE
Replicate support

### ISSUE THREAD

**Issue by platform-kit** [Camb-ai/MARS5-TTS#40]
I see there's an official demo of Mars5 on Replicate

https://replicate.com/camb-ai/mars5-tts

Could you add the cog.yaml and predict.py files that were used to create that demo to this repo? That way users like myself who use replicate can riff on the code in a way that makes it easier to share and host demos of results.

**Comment by arnavmehta7** [comment]
Hey @platform-kit 
https://github.com/Camb-ai/MARS5-TTS/pull/41

This PR has been merged and you can find the code under `cog` folder.
There's a TODO to stop uploading the file as a "temporary link", returning the Path for the audio didn't work for us, someone can try taking that up :)

**Comment by mattt** [comment]
@arnavmehta7 What error were you getting when you returned a `Path` directly?

**Comment by arnavmehta7** [comment]
@mattt It was showing some "failed to decode bytesUrl" when I was using Path.

**Comment by arnavmehta7** [comment]
```
>>>>> Saving file at /tmp/aud.wav, sr: self.mars5.sr
ⅹ Failed to decode dataurl: missing data prefix
```
@mattt specific logs if needed

**Comment by arnavmehta7** [comment]
@platform-kit Are you still keen to raise a PR with the fix 🙂

**Comment by RF5** [comment]
I believe this is fixed now.
