### ISSUE TITLE
Running locally?

### ISSUE THREAD

**Issue by chrisbward** [Camb-ai/MARS5-TTS#51]
Hi - just setting this up on my machine (baremetal / pyenv 3.10) and have just noticed that there is no inference script, jupyter notebook or gradio demo to verify the install?

If I can find the time I would reverse engineer what's happening here to write the script - but do you have this at hand already?

**Comment by RF5** [comment]
Hi @chrisbward , a bit unsure what you're looking for? The inference code is given in the [inference.py](https://github.com/Camb-ai/MARS5-TTS/blob/master/inference.py) script, and we link a colab jupyter notebook in the readme to load and try it out yourself (link [here](https://github.com/Camb-ai/MARS5-TTS/blob/master/mars5_demo.ipynb)). 

What are you looking for specifically?

**Comment by pvpshoot** [comment]
i think he want smth like this https://179c54d254f7.ngrok.app/

**Comment by chrisbward** [comment]
usually it's either a gradio demo (as above), or a command line utility; `inference-cli.py --model-path=foo --etc-etc=bar sample text to speak`

this is usually a good entrance point to reverse the python code for the casuals (like me)

as an aside - well done for including the python version in the docs (you'd be surprised!)
