### ISSUE TITLE
Can you share gradio app please to run locally

### ISSUE THREAD

**Issue by FurkanGozukara** [Camb-ai/MARS5-TTS#52]
there is this link https://179c54d254f7.ngrok.app/ 

which didnt load for me

but i assume it is gradio

can you share it ? thank you

**Comment by akshhack** [comment]
Hey @FurkanGozukara this is now fixed, thanks!

**Comment by FurkanGozukara** [comment]
@akshhack what is the maximum input audio duration it can utilize? only 5 sec 30 sec?

what audio duration we can max provide to get best voice cloning performance?

**Comment by FurkanGozukara** [comment]
@akshhack link is dead again

can we get gradio demo code?
