### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by victorchall** [Camb-ai/MARS5-TTS#57]
Noting `We are open-sourcing MARS5 in English under GNU AGPL 3.0, but you can request to use it under a different license by emailing [help@camb.ai](mailto:help@camb.ai).`

Keep in mind, if you are accepting third party contributions on github, the offering of another licenses is very dubious.  You should consult a lawyer before you do so.

I have a PR for fixing the numpy requirement, and honestly I don't care (it's one line fixing a trivial bug, whatever), but others might care and it opens you to potential lawsuits from contributors by relicensing their contributions without their authorization.

**Comment by akshhack** [comment]
Hey @victorchall thanks for the advice. We are well informed and have an excellent legal team. Thank you!

**Comment by githebs** [comment]
Hey @akshhack I'm wondering how you're dealing with that since there are no CLAs or something, how do you incorporate external commits ? I want to do the same for my upcoming projects, your input is appreciated
