### ISSUE TITLE
pretraining/finetune

### ISSUE THREAD

**Issue by cesinsingapore** [Camb-ai/MARS5-TTS#58]
in case people would like to contribute adding another english accent or another languages, which documents should they refer ?

**Comment by kunci115** [comment]
agree

**Comment by RF5** [comment]
Appologies, I'm not too sure what this question means? What do you mean 'which documents should they refer'?

**Comment by nivibilla** [comment]
I think he means if there is any docs/info on how to pretrain it or fine-tune
