### ISSUE TITLE
Too much inference time

### ISSUE THREAD

**Issue by shivgit07** [Camb-ai/MARS5-TTS#61]
I was running the quickstart demo on colab but the Synthesis step is taking too much time to run, even when I try runing it for shallow clone. Is there any possible way to fix this?

**Comment by akshhack** [comment]
@shivgit07 there's nothing really to "fix" -- you do need a GPU to run this, plus we're open to contributions on making the system faster and have written down tasks that folks can take up in https://github.com/Camb-ai/MARS5-TTS/discussions/39
