### ISSUE TITLE
how to train the model and ft it

### ISSUE THREAD

**Issue by deyituo** [Camb-ai/MARS5-TTS#63]
how to train the model and ft it

**Comment by akshhack** [comment]
Hey @deyituo we haven't released the training code yet due to bandwidth. Our community focus right is to improve inference speeds and stability for which we've release a roadmap and are open for contributors
https://github.com/Camb-ai/MARS5-TTS/discussions/39

**Comment by eschmidbauer** [comment]
im also interested in training. any chance training code will be released ?

**Comment by henriklied** [comment]
Also wondering about this, @akshhack.
