### ISSUE TITLE
部署

### ISSUE THREAD

**Issue by Chaineselion** [Camb-ai/MARS5-TTS#66]
本地部署总是不成功，有没有启动包或者安装包之类的？

**Comment by NourAlMerey** [comment]
您能给我们提供更多详细信息吗？您在本地运行时到底遇到了什么？

**Comment by Chaineselion** [comment]
> 您能为更多人提供什么帮助？您在本地到底遇到了什么
环境部署不成功，编程小白不懂如何简单部署整合包，我希望在另一台电脑上也能运行，也就是部署成一件整合包。

**Comment by NourAIMerey** [comment]
所以你是说它没有在你的本地机器上运行，对吗？您可以尝试运行 Colab Notebook 吗？那应该更容易。
