### ISSUE TITLE
Voice cloning failed when reference transcript is not provided

### ISSUE THREAD

**Issue by yyyy2023** [Camb-ai/MARS5-TTS#71]
The quality is really bad when reference transcript is not provided, even in the mars5_demo notebook. 

However, it works well on the official mars5 speech emulation demo website, even when the reference transcript is not provided. 

Does it use tools like whisper to generate the audio transcript first? 

Thanks!

**Comment by NourAIMerey** [comment]
We're releasing a new much better version (MARS6). Stay tuned and let us know your thoughts when it's released.
