### ISSUE TITLE
Code for finetuning

### ISSUE THREAD

**Issue by cene555** [Camb-ai/MARS5-TTS#72]
I want to fine-tune MARS5 on my own data. Do you have code to do this?

**Comment by NourAIMerey** [comment]
We won't be releasing the finetuning code for MARS5. But we're releasing a new much better model soon (MARS6), and might release the finetuning code for it.

**Comment by changeling** [comment]
> We won't be releasing the finetuning code for MARS5. But we're releasing a new much better model soon (MARS6), and might release the finetuning code for it.

Do you have a loose timeframe for MARS6 release?

**Comment by platform-kit** [comment]
@NourMerey just wondering about the ETA for Mars6? And will it include finetuning scripts at launch?
