### ISSUE TITLE
Support for Russian and Kazakh

### ISSUE THREAD

**Issue by iowathe3rd** [Camb-ai/MARS5-TTS#77]
Hello!
I want to use your tts locally in my project, but I need support for eng, russian and kazakh. Is there any documentation on these languages ​​in Mars5?

**Comment by NourAIMerey** [comment]
We only released the English version of Mars5 for now. We haven't decided when other languages will be released. But please feel free to contribute and create a pull request. Also, we'd love to hear what developers are using Mars5 for; so feel free to share your ideas in the 🙌 [Show and tell](https://github.com/Camb-ai/MARS5-TTS/discussions/categories/show-and-tell).
