### ISSUE TITLE
Takes too long to process. Optimizations needed.

### ISSUE THREAD

**Issue by bigbrotherr** [Camb-ai/MARS5-TTS#80]
Takes too long for deep clone to finish processing even for a simple text (i9+ 32gb, RTX 3080 12gb) and the result is also not that good. We need optimizations. Shallow clone does not work. The output is something else other than the text provided.
[output_audio.zip](https://github.com/user-attachments/files/16403315/output_audio.zip)

**Comment by NourAIMerey** [comment]
MARS5 is not optimized for speed. Try running our Colab notebook, that might be faster. We're also releasing MARS6 soon, an optimized model in terms of speed and output quality; so keep an eye on it!
